;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        org-self-insert-command
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        goto-line
        helm-M-x
        helm-mini
        mouse-set-region
        sp-backward-delete-char
        ))
